package vku.duongdlt.winktraveller.model

data class Tour(
    val id: Int=0,
    val tour_create_date :String="",
    val tour_description:String="",
    val tour_duration:Int=0,
    val tour_edit_date:String="",
    val tour_end_date:String="",
    val tour_highlights:String="",
    val tour_image_url:String="",
    val tour_includes:String="",
    val tour_introduction:String="",
    val tour_journey:String="",
    val tour_location_id:String="",
    val tour_location_name:String="",
    val tour_max_capacity:Int=0,
    val tour_name:String="",
    val tour_number_of_rating:Int= 0,
    val tour_price:Float=0.0f,
    val tour_registration:Int=0,
    val tour_schedule:String="",
    val tour_star:Float=0.0f,
    val tour_start_date:String="",
    val tour_starting_point:String="",
    val tour_status:String="",
    val tour_status_id:String="",
    val tour_total_view:Int=0,
    val tour_vehicle:String="",
    val url:String=""
)